### ISSUE TITLE
Installing and setting up

### ISSUE THREAD

**Issue by fakelawface** [afernandezb92/2FAGmailPhising#1]
Hello, i'm new with python and linux but i know enought to say you did a awesome job!
 Like i said i'm new with that stuff and i need to ask, could you please make a fast tutorial/guide to install and set it up on kali linux?

 Thank you very much!

**Comment by afernandezb92** [comment]
Hello,

You must move the repo to apache directory and run apache server.

PD. Is necesary install requirements.

In the future, i write "How to run" section.

**Comment by afernandezb92** [comment]
i have just created the "how to run section"
