### ISSUE TITLE
How to run section

### ISSUE THREAD

**Issue by VSGuy** [afernandezb92/2FAGmailPhising#2]
Hey! first of all i've to say that i loved your project and the way it alerts that 2FAs are easily bypassed.

 I'm very sorry to disturb you, but you have any estimate time to make a "How to run section"? I'm very anxious to make it run here.

 Last question, there's any way to donate?

 Thank you!

**Comment by afernandezb92** [comment]
i have just created the "how to run section"

Thanks!
